
// This file is automatically generated by Clarigen.
// Don't make changes to this file, or they'll
// be overwritten.
import { factory } from "https://deno.land/x/clarigen@v0.4.14/mod.ts";
import { simnet } from "./../artifacts/clarigen/index.ts";

export const { test, contracts, accounts } = factory(simnet);

export const {
  counter,
  ftTrait,
  tester
} = contracts;
