
// This file is automatically generated by Clarigen.
// Don't make changes to this file, or they'll
// be overwritten.
export {
  Chain,
  err,
  factory,
  hexToBytes,
  ok,
  tx,
  txErr,
  txOk,
} from "https://deno.land/x/clarigen@v0.4.10/mod.ts";
import { factory } from "https://deno.land/x/clarigen@v0.4.10/mod.ts";
import { simnet } from "./../artifacts/clarigen/index.ts";

export const { test, contracts, accounts } = factory(simnet);

export const {
  counter,
  ftTrait,
  tester
} = contracts;
