import { resolve } from '../src/deps.ts';

const sourceFile = resolve(Deno.cwd(), 'src/types.ts');
const sourceCode = await Deno.readTextFile(sourceFile);

const output = `export const types = \`
${sourceCode}
\`;
`;

const outputFile = resolve(Deno.cwd(), 'src/cli/type-stub.ts');
await Deno.writeTextFile(outputFile, output);

const tomlInitPath = resolve(Deno.cwd(), 'src/cli/files/init-config.toml');
const tomlInit = (await Deno.readTextFile(tomlInitPath)).replaceAll('`', '\\`');

const tomlCode = `// This file is automatically generated from the
// contents of \`./init-config.toml\`

export const tomlInit = \`
${tomlInit}
\`;
`;

const tomlStubFile = resolve(Deno.cwd(), 'src/cli/files/init-config.ts');
await Deno.writeTextFile(tomlStubFile, tomlCode);
